/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Bitexco = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/bitexco.glb')
  return (
    <group ref={buildingRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.Blue}
        position={[0, 4.79, 0.58]}
      />
    </group>
  )
})

export default Bitexco

useGLTF.preload('/models/bitexco.glb')
