/* eslint-disable react/prop-types */
/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { forwardRef, useState } from 'react'
import { useCursor, useGLTF } from '@react-three/drei'

const Building1 = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/building-1.glb')
  const [hovered, setHover] = useState(false)
  useCursor(hovered)

  return (
    <group
      onPointerOver={(e) => (e.stopPropagation(), setHover(true))}
      onPointerOut={() => setHover(false)}
      ref={buildingRef}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
      />
    </group>
  )
})

export default Building1

useGLTF.preload('/building-1.glb')
