/* eslint-disable react/display-name */
/* eslint-disable no-undef */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Building4 = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/building-4.glb')
  return (
    <group ref={buildingRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.002']}
      />
    </group>
  )
})

export default Building4

useGLTF.preload('/building-4.glb')
