/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Building5 = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/building-5.glb')
  return (
    <group ref={buildingRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.003']}
      />
    </group>
  )
})

export default Building5

useGLTF.preload('/building-5.glb')
