/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Building2 = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/building-2.glb')
  return (
    <group ref={buildingRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.002']}
      />
    </group>
  )
})

export default Building2

useGLTF.preload('/building-2.glb')
