/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Fansipan = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/fansipan.glb')
  return (
    <group ref={buildingRef} scale={[3, 3, 3]} {...props} dispose={null}>
      <mesh
        geometry={nodes.Landscape_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        geometry={nodes.Landscape_2.geometry}
        material={materials['Material.002']}
      />
      <mesh
        geometry={nodes.Landscape_3.geometry}
        material={materials['Material.003']}
      />
    </group>
  )
})

export default Fansipan

useGLTF.preload('/models/fansipan.glb')
