/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Lake = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/lake.glb')
  return (
    <group ref={buildingRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Vert_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        geometry={nodes.Vert_2.geometry}
        material={materials['Material.002']}
      />
    </group>
  )
})

export default Lake

useGLTF.preload('/models/lake.glb')
