/* eslint-disable react/display-name */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Tree4 = forwardRef((props, buildingRef) => {
  const { nodes, materials } = useGLTF('/models/tree-4.glb')
  return (
    <group
      ref={buildingRef}
      scale={[0.25, 0.25, 0.25]}
      {...props}
      dispose={null}
    >
      <group position={[0, 1.37, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-15.62, -5.88, 8.33]}
          rotation={[0.31, 0.01, -0.52]}
          scale={[2.72, 2.72, 2.72]}
        >
          <group position={[4.39, 3.68, -0.29]}>
            <mesh
              geometry={nodes.Cylinder004.geometry}
              material={materials['Material.006']}
            />
            <mesh
              geometry={nodes.Cylinder004_1.geometry}
              material={materials['Material.005']}
            />
          </group>
        </group>
      </group>
    </group>
  )
})

export default Tree4

useGLTF.preload('/models/tree-4.glb')
